# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=3.1.2.9
last_mod_version=3.1.2.8

# Common
minecraft_version=1.18.2
minecraft_short_version=1.18
java_version=17
mixin_version=0.8.5

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2022.11.06

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=40.3.11
forge_version_range=[40,)
forge_mc_version_range=[1.18.2,1.18.3)

# Integration Mods
jei_version=10.2.1.1009
mantle_version=1.9.54
tic_version=3.7.2.167
probe_version=5.1.2-9
terrablender_version=3816497
byg_version=3956521
patchouli_version=1.18.2-71.1
patchouli_provider_version=1.18.2-1.0.6-Snapshot.4

# Mod options
mod_name=SurvivalistEssentials
mod_id=survivalistessentials
mod_author=wendall911
mod_credits=ashar42 billyzekat
license=MIT
issue_tracker=https://github.com/wendall911/SurvivalistEssentials/issues
mod_description=A small mod to make the first day or two of play more believable. New early game tools, no tree punching, saws, and more!
mod_update_branch=1.18.2

# CurseForge/Modrinth Options
release_type=release
release_versions=1.18.2
