# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
mod_name=SurvivalistEssentials
modid=survivalistessentials
mod_version=6.2.3.4
last_mod_version=6.2.3.3
java_version=17

# Common
minecraft_version=1.20.1
minecraft_short_version=1.20
mixin_version=0.8.5

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2023.09.03

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=47.4.8
forge_version_range=[46,)
forge_mc_version_range=[1.20,1.20.2)

# Integration Mods
jei_version=15.20.0.112
mantle_version=1.11.79
tic_version=3.10.2.92
ts_version=1.20.1-5.0.0.2
bop_version=4617260
terrablender_version=5378180
byg_version=5910111
tyg_version=5630466
corgilib_version=5691268
geckolib_version=4.4.9
probe_version=6106996
carryon_version=4628675
cyanide_version=4584675
patchouli_version=1.20.1-84.1
patchouli_provider_version=1.20.1-1.0.9-Snapshot.1
curios_version=5.14.1
regions_version=5558225

# Mod options
mod_author=wendall911
issue_tracker=https://github.com/wendall911/SurvivalistEssentials/issues
license=MIT
display_name=Survivalist Essentials
description=A small mod to make the first day or two of play more believable. New early game tools, no tree punching, saws, and more!
display_url=https://github.com/wendall911/SurvivalistEssentials
mod_update_branch=1.20.1
authors=wendall911
credits=ashar42 billyzekat
logo_file=logo.png
maven_url=https://maven.pkg.github.com/wendall911/SurvivalistEssentials

# CurseForge/Modrinth Options
release_type=release
release_versions=1.20.1
