# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
mod_version=6.2.1.3
last_mod_version=6.2.1.2

# Common
minecraft_version=1.21.4
whitenoise_version=1.1.1
whitenoise_range=[1.0.0, 2.0.0)
mixin_version=0.8.5
java_version=21

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2025.03.23

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.4.40-beta
neoforge_loader_version_range=[21.0.143,)
neoforge_mc_version_range=[1.21.3, 1.22)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809

# Integration Mods
ts_version=6.+
mantle_version=1.11.+
tic_version=3.9.+
jei_version=20.0.0.4
bop_version=5489686
terrablender_version=5861339
glitch_core_version=5483773
byg_version=???
tyg_version=???
corgilib_version=???
geckolib_version=4.7.1
probe_version=12.0.3-5
carryon_version=5541347
patchouli_version=1.21-87
patchouli_provider_version=???
curios_version=???
regions_version=???
create_neoforge_version=???

# Mod options
mod_id=survivalistessentials
mod_name=SurvivalistEssentials
mod_author=wendall911
license=MIT
display_name=Survivalist Essentials
display_url=https://github.com/wendall911/SurvivalistEssentials
mod_description=A small mod to make the first day or two of play more believable. New early game tools, no tree punching, saws, and more!
mod_credits=ashar42 billyzekat
issue_tracker=https://github.com/wendall911/SurvivalistEssentials/issues
mod_update_branch=1.21

# CurseForge/Modrinth Options
release_type=release
release_versions=1.21.4
