modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${license}"
logoBlur=false
issueTrackerURL="${issue_tracker}"

[[mods]]
    modId="${modid}"
    displayName="${display_name}"
    description="${description}"
    version="${version}"
    displayURL="${display_url}"
    updateJSONURL="https://raw.githubusercontent.com/wendall911/SurvivalistEssentials/${mod_update_branch}/files/updates.json"
    authors="${authors}"
    credits="${credits}"
    itemIcon="survivalistessentials:rock_stone"
    logoFile="${logo_file}"
[[dependencies.${modid}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modid}]]
    modId="fruittrees"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="quark"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="allyoucaneat"
    mandatory=false
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="watersource"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="sushigocrafting"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="botania"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="ars_nouveau"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="geckolib3"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="undergarden"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="biomeswevegone"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="twilightforest"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="ecologics"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="aquaculture"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="malum"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="iceandfire"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="regions_unexplored"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
